@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNjUzZDg2OTNlMjU0ZTk5MWE0OTdlYTg2IiwiaWF0IjoxNjk5NDQ0MDEwLCJleHAiOjE2OTk1MzA0MTB9.QNDwqT_2lyG68ylcSG-hRLJABcyepPNc80m6ptfy6sk

POST http://localhost:8080/users/register HTTP/1.1
content-type: application/json

{
    "username": "testtest",
    "password": "test!"
}
###
POST http://localhost:8080/users/login HTTP/1.1
content-type: application/json

{
    "username": "testtest",
    "password": "test!"
}
###
POST http://localhost:8080/evnets/create HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
{
    "eventName": "test",
    "date": "",
    "location": "",
    "host": "Test Testicles",
    "creator": "",
    "maxParticipants": "",
    "image": ""
}