
POST http://localhost:8080/users/register HTTP/1.1
content-type: application/json

{
    "username": "testtest",
    "password": "test!"
}
###
POST http://localhost:8080/users/login HTTP/1.1
content-type: application/json

{
    "username": "testtest",
    "password": "test!"
}
###
POST http://localhost:8080/events/create HTTP/1.1
content-type: application/json

{
    "eventName": "test",
    "date": "",
    "location": "",
    "host": "Test Testicles",
    "creator": "",
    "maxParticipants": "",
    "image": ""
}
###
POST http://localhost:8080/users/verify HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNjUzZDg2OTNlMjU0ZTk5MWE0OTdlYTg2IiwiaWF0IjoxNjk5NTMxNzAxfQ.8kC3sw3tRefxoNsHrJCPTnR7pk9-pfc4wba_wPNz1vU


###
POST http://localhost:8080/types/create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNjUzZDg2OTNlMjU0ZTk5MWE0OTdlYTg2IiwiaWF0IjoxNjk5NTMxNzAxfQ.8kC3sw3tRefxoNsHrJCPTnR7pk9-pfc4wba_wPNz1vU

{
    "typeName": "indoors"
}
###