
POST http://localhost:8080/api/users/register HTTP/1.1
content-type: application/json

{
    "username": "testtest",
    "password": "test!"
}
###

GET http://localhost:8080/api/events/getRandomEvents/5 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNjUzZDg2OTNlMjU0ZTk5MWE0OTdlYTg2IiwiaWF0IjoxNjk5NTMxNzAxfQ.8kC3sw3tRefxoNsHrJCPTnR7pk9-pfc4wba_wPNz1vU

###

POST http://localhost:8080/api/users/login HTTP/1.1
content-type: application/json

{
    "username": "testtest",
    "password": "test!"
}
###
POST http://localhost:8080/api/events/create HTTP/1.1
content-type: application/json

{
    "eventName": "test",
    "date": "",
    "location": "",
    "host": "Test Testicles",
    "creator": "",
    "maxParticipants": "",
    "image": ""
}
###
POST http://localhost:8080/api/users/verify HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNjUzZDg2OTNlMjU0ZTk5MWE0OTdlYTg2IiwiaWF0IjoxNjk5NTMxNzAxfQ.8kC3sw3tRefxoNsHrJCPTnR7pk9-pfc4wba_wPNz1vU


###
POST http://localhost:8080/api/types/create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNjUzZDg2OTNlMjU0ZTk5MWE0OTdlYTg2IiwiaWF0IjoxNjk5NTMxNzAxfQ.8kC3sw3tRefxoNsHrJCPTnR7pk9-pfc4wba_wPNz1vU

{
    "typeName": "water"
}
###
PUT http://localhost:8080/api/types/update HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNjUzZDg2OTNlMjU0ZTk5MWE0OTdlYTg2IiwiaWF0IjoxNjk5NTMxNzAxfQ.8kC3sw3tRefxoNsHrJCPTnR7pk9-pfc4wba_wPNz1vU

{
    "id": "654cd5975e7518d932ddc594",
    "newName": "football"
}
###
POST http://localhost:8080/api/events/create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNjUzZDg2OTNlMjU0ZTk5MWE0OTdlYTg2IiwiaWF0IjoxNjk5NTMxNzAxfQ.8kC3sw3tRefxoNsHrJCPTnR7pk9-pfc4wba_wPNz1vU

{
    "eventName": "Football",
    "description": "We warm up together and then play",
    "date": "2023-11-10T16:30:00Z",
    "location": {
        "type": "Point",
        "coordinates": [125.6, 10.1]
    },
    "locationName": "someplace",
    "host": "Test Testes",
    "maxParticipants": 20,
    "duration": 90
}
###
POST http://localhost:8080/api/tags/create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNjUzZDg2OTNlMjU0ZTk5MWE0OTdlYTg2IiwiaWF0IjoxNjk5NTMxNzAxfQ.8kC3sw3tRefxoNsHrJCPTnR7pk9-pfc4wba_wPNz1vU

{
    "tagName": "Strenght"
}
###
POST http://localhost:8080/api/categories/create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNjUzZDg2OTNlMjU0ZTk5MWE0OTdlYTg2IiwiaWF0IjoxNjk5NTMxNzAxfQ.8kC3sw3tRefxoNsHrJCPTnR7pk9-pfc4wba_wPNz1vU

{
    "categoryName": "Baseball"
}